# Generated by Django 2.0.5 on 2018-06-18 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='nazwa')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='saldo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name_plural': 'konta',
                'verbose_name': 'konto',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Account')),
            ],
            options={
                'verbose_name_plural': 'kategorie',
                'ordering': ['name'],
                'verbose_name': 'kategoria',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='kurs')),
            ],
            options={
                'verbose_name_plural': 'waluty',
                'verbose_name': 'waluta',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=True, verbose_name='właściciel')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uprawnienia',
            },
        ),
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='tytuł')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='kwota')),
                ('next_date', models.DateField(default=datetime.date.today, verbose_name='data następnego wykonania')),
                ('frequency', models.IntegerField(verbose_name='częstotliwość')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Account')),
                ('categories', models.ManyToManyField(to='mainapp.Category', verbose_name='kategoria')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Currency', verbose_name='waluta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'zlecenia stałe',
                'ordering': ['next_date'],
                'verbose_name': 'zlecenie stałe',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='tytuł')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='kwota')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Account')),
                ('categories', models.ManyToManyField(to='mainapp.Category', verbose_name='kategoria')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Currency', verbose_name='waluta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'transakcje',
                'ordering': ['-date'],
                'verbose_name': 'transakcja',
            },
        ),
    ]
