# Generated by Django 2.0.6 on 2018-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180610_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standingorder',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='tytuł'),
        ),
    ]
